export const AUTHORITIES = {
  ADMIN: 'ROLE_ADMIN',
  USER: 'ROLE_USER',
  SYSTEM_ADMIN: 'ROLE_SYSTEM_ADMIN',
  DASHBOARD: 'PERMISSION_DASHBOARD',
  STAFFROLE: 'PERMISSION_STAFFROLE',
  STAFF: 'PERMISSION_STAFF',
  MENUITEM: 'PERMISSION_MENUITEM',
  TABLE: 'PERMISSION_TABLE',
  BILL_VIEW_ONLY: 'PERMISSION_BILL_VIEWONLY',
  BILL_FULL_ACCESS: 'PERMISSION_BILL_FULLACCESS',
  ORDER_ADD_AND_CANCEL: 'PERMISSION_ORDER_ADD_AND_CANCEL',
  ORDER_CHECKOUT: 'PERMISSION_ORDER_CHECKOUT',
  ORDER_DISCOUNT: 'PERMISSION_ORDER_DISCOUNT',
  KITCHEN_PREPARING_ITEM: 'PERMISSION_KITCHEN_PREPARING_ITEM',
  KITCHEN_RTS_ITEM: 'PERMISSION_KITCHEN_RTS_ITEM',
};

export const messages = {
  DATA_ERROR_ALERT: 'Internal Error',
};

export const APP_DATE_FORMAT = 'DD/MM/YY HH:mm';
export const APP_TIMESTAMP_FORMAT = 'DD/MM/YY HH:mm:ss';
export const APP_LOCAL_DATE_FORMAT = 'DD/MM/YYYY';
export const APP_LOCAL_DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm';
export const APP_WHOLE_NUMBER_FORMAT = '0,0';
export const APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT = '0,0.[00]';
