export const AUTHORITIES = {
  ADMIN: 'ROLE_ADMIN',
  USER: 'ROLE_USER',
  SYSTEM_ADMIN: 'ROLE_SYSTEM_ADMIN',
  STAFFROLE_VIEW: 'PERMISSION_STAFFROLE_VIEW',
  STAFFROLE_CREATE: 'PERMISSION_STAFFROLE_CREATE',
  STAFFROLE_EDIT: 'PERMISSION_STAFFROLE_EDIT',
  STAFFROLE_DELETE: 'PERMISSION_STAFFROLE_DELETE',
  STAFF_VIEW: 'PERMISSION_STAFF_VIEW',
  STAFF_CREATE: 'PERMISSION_STAFF_CREATE',
  STAFF_EDIT: 'PERMISSION_STAFF_EDIT',
  STAFF_DELETE: 'PERMISSION_STAFF_DELETE',
  MENUITEM_VIEW: 'PERMISSION_MENUITEM_VIEW',
  MENUITEM_CREATE: 'PERMISSION_MENUITEM_CREATE',
  MENUITEM_EDIT: 'PERMISSION_MENUITEM_EDIT',
  MENUITEM_DELETE: 'PERMISSION_MENUITEM_DELETE',
  TABLE_VIEW: 'PERMISSION_TABLE_VIEW',
  TABLE_CREATE: 'PERMISSION_TABLE_CREATE',
  TABLE_EDIT: 'PERMISSION_TABLE_EDIT',
  TABLE_DELETE: 'PERMISSION_TABLE_DELETE',
  BILL_VIEW: 'PERMISSION_BILL_VIEW',
  BILL_EDIT: 'PERMISSION_BILL_EDIT',
  BILL_DELETE: 'PERMISSION_BILL_DELETE',
  ORDER_WAITER: 'PERMISSION_ORDER_WAITER',
  ORDER_DISCOUNT: 'PERMISSION_ORDER_DISCOUNT',
  ORDER_PAYMENT: 'PERMISSION_ORDER_PAYMENT',
};

export const messages = {
  DATA_ERROR_ALERT: 'Internal Error',
};

export const APP_DATE_FORMAT = 'DD/MM/YY HH:mm';
export const APP_TIMESTAMP_FORMAT = 'DD/MM/YY HH:mm:ss';
export const APP_LOCAL_DATE_FORMAT = 'DD/MM/YYYY';
export const APP_LOCAL_DATETIME_FORMAT = 'YYYY-MM-DDTHH:mm';
export const APP_WHOLE_NUMBER_FORMAT = '0,0';
export const APP_TWO_DIGITS_AFTER_POINT_NUMBER_FORMAT = '0,0.[00]';
